name: Deploy to GitHub Pages

on:
  push:
    branches: 'main'

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: yarn install

      - name: Build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        run: yarn run build

      - name: Upload Artifacts for Deployment
        uses: actions/upload-pages-artifact@v3
        with:
          # this should match the `pages` option in the adapter-static options
          path: 'build'
          name: 'artifact'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: 'artifact'
